[package]
name = "derive-pinned"
version = "0.1.0"
authors = ["boats <boats@mozilla.com>"]

[dependencies]
synstructure = "0.8.1"
syn = "0.13.4"
quote = "0.5.2"
proc-macro2 = "0.3.8"

[lib]
proc-macro = true
